### ISSUE TITLE
Logo offer

### ISSUE THREAD

**Issue by familqasimov** [dangquanuet/The-Movie-DB-Kotlin#50]
Hi
I'm designing for open source projects and I'm trying to expand my design tecnigue with these jobs. I want to design an icon for your project. I have a few ideas in my mind, I hope you accept and I do them. Please let me know if you have any ideas. In this way, we create a logo that will make you happy.
If you want, you can look at my repositories.
https://github.com/familqasimov?tab=overview&from=2018-06-01&to=2018-06-30

Best regards.
Famil

**Comment by dangquanuet** [comment]
Hi,
Thank you so much but this is a sample project I use for testing new Android code and training newbies. So I think logo is not necessary.
Again thank you for your interest.

Best regards.
Quan
