### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by jamalbaharun** [dangquanuet/The-Movie-DB-Kotlin#75]
Hello Dangquanuet!

I really admire your work. I am trying to implement your pattern in my project. but I have a problem in navigation. for example when I will navigate from main to splash. i experience error "is unknown to this NavController". can you give me a guide?

**Comment by dangquanuet** [comment]
Do you have action from main to splash in navigation graph?

**Comment by jamalbaharun** [comment]
![image](https://user-images.githubusercontent.com/5465560/64007825-11970980-cb3f-11e9-9f64-027c1a8d7343.png)
yes its my navigation graph, and this is my code to navigation from main to login

![image](https://user-images.githubusercontent.com/5465560/64007894-2ffd0500-cb3f-11e9-92c1-a4c7b31c705e.png)

its error the occure
![image](https://user-images.githubusercontent.com/5465560/64007925-499e4c80-cb3f-11e9-9258-c98f09c80b73.png)

can you help me?

**Comment by dangquanuet** [comment]
Can you try replace
`view?.let { navigate }`
with
`findNavController().navigate(MainFragmentDirections.mainToLogin())`

**Comment by jamalbaharun** [comment]
it still happen and the error still the same

![image](https://user-images.githubusercontent.com/5465560/64008982-3db38a00-cb41-11e9-886b-8228cc6295f7.png)

where is the wrong?

**Comment by dangquanuet** [comment]
@jamalbaharun can you show me the code action main_to_login in nav graph?

**Comment by jamalbaharun** [comment]
![image](https://user-images.githubusercontent.com/5465560/64009649-6e47f380-cb42-11e9-9d92-7655aa90405c.png)

![image](https://user-images.githubusercontent.com/5465560/64009695-84ee4a80-cb42-11e9-9116-843b5549c32c.png)

@dangquanuet

**Comment by jamalbaharun** [comment]
can u give me and example from your project? so i can replicate in my project @dangquanuet :D

**Comment by dangquanuet** [comment]
with above info, i can not see what wrong or tell you how to fix? Can you provide more info or source code?

**Comment by jamalbaharun** [comment]
do you want a full source code? i will sent u the full source code to your email. please give me your email @dangquanuet

**Comment by dangquanuet** [comment]
my email is dangquanuet@gmail.com

**Comment by jamalbaharun** [comment]
before that i experiment with you project and still encunter that error, i navigate from main to splash like this

![image](https://user-images.githubusercontent.com/5465560/64014877-79ece780-cb4d-11e9-9cd9-1c448800dec2.png)

![image](https://user-images.githubusercontent.com/5465560/64014903-8b35f400-cb4d-11e9-9c54-d4548451eac6.png)

and error like this

![image](https://user-images.githubusercontent.com/5465560/64014938-9db02d80-cb4d-11e9-91e3-46b6b5e9370c.png)

can you explain why?

**Comment by dangquanuet** [comment]
I think setupNavHost is wrong,
because my project is structured with 3 tabs in main fragment, and i use KeepStateNavigator to keep my tab state.
But in your project, i think you do not need to configure like that, just follow steps from android guide at https://developer.android.com/guide/navigation/navigation-getting-started

**Comment by dangquanuet** [comment]
navigation basic sample project
https://github.com/googlesamples/android-architecture-components/tree/master/NavigationBasicSample

**Comment by jamalbaharun** [comment]
thanks a lot for your advice, realy apperciate that @dangquanuet

**Comment by jamalbaharun** [comment]
do your have any recomend libarry for event bus? @dangquanuet

**Comment by dangquanuet** [comment]
It's okay, if you need to use, just use it :)

**Comment by hashimTahir** [comment]
Hello @dangquanuet 
i was going through this app, i have couple of questions, or maybe they are issues, Didn't want to open new issues without asking first.
1->The MainActivity graph has splashfragment as its start destination. which then leads to pagingMovie fragment and popular movies fragment. There are other fragments there including movielistPager and moviePager. but they are not connected to anything.

![image](https://user-images.githubusercontent.com/35306807/121782359-8cb99a80-cbc2-11eb-8612-e115815b3004.png)

2-> One can favorite the movie by opening the detail page and clicking floating action button. but there is no option to view the favorite movies.

3->Shouldn't there be a search option to search the movies.

4-> If i connect the navigation, to pager fragments, it only shows insta like cards and no tabs. Shouldn't the splash lead to the pager as main landing page with popular, top rated and favourite tabs.?
If so, then may i add or fix some or all of those features.
